FROM ubuntu
# Comentario - para fazer instalação junto
# atualização, deve se usar &&
# exemplo: RUN apt update && apt install curl --yes && apt install vim --yes
RUN apt update
RUN apt install curl --yes

